apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mind-eden-ingress
  namespace: mind-eden-ns
  labels:
    app: mind-eden
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/gzip-types: "text/plain,text/css,application/json,application/javascript,text/xml,application/xml,application/xml+rss,text/javascript"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mind-eden.qianxue.online
    secretName: mind-eden-tls-secret
  rules:
  - host: mind-eden.qianxue.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mind-eden-service
            port:
              number: 80
